//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaxSender.SendFAXGatewayWebReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/SendFa" +
        "xGatewayWebService/1.0", ConfigurationName="SendFAXGatewayWebReference.SendFAXGatewayHttpServiceSoap")]
    public interface SendFAXGatewayHttpServiceSoap {
        
        // CODEGEN: Generating message contract since the operation SendFAX is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FaxSender.SendFAXGatewayWebReference.SendFAXResponse1 SendFAX(FaxSender.SendFAXGatewayWebReference.SendFAXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<FaxSender.SendFAXGatewayWebReference.SendFAXResponse1> SendFAXAsync(FaxSender.SendFAXGatewayWebReference.SendFAXRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/SendFa" +
        "xGatewayWebService/1.0")]
    public partial class SendFAX : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SendOutboundFAXType sendOutboundFAXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
            "eway/1.0", Order=0)]
        public SendOutboundFAXType SendOutboundFAX {
            get {
                return this.sendOutboundFAXField;
            }
            set {
                this.sendOutboundFAXField = value;
                this.RaisePropertyChanged("SendOutboundFAX");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
        "eway/1.0")]
    public partial class SendOutboundFAXType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passWordField;
        
        private string destinationField;
        
        private string priorityField;
        
        private string receiptField;
        
        private string senderField;
        
        private string faxRequestDateTimeField;
        
        private Document[] documentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
                this.RaisePropertyChanged("PassWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("Destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=3)]
        public string Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Receipt {
            get {
                return this.receiptField;
            }
            set {
                this.receiptField = value;
                this.RaisePropertyChanged("Receipt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FaxRequestDateTime {
            get {
                return this.faxRequestDateTimeField;
            }
            set {
                this.faxRequestDateTimeField = value;
                this.RaisePropertyChanged("FaxRequestDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Document[] Documents {
            get {
                return this.documentsField;
            }
            set {
                this.documentsField = value;
                this.RaisePropertyChanged("Documents");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
        "eway/1.0")]
    public partial class Document : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string seqNumberField;
        
        private string documentIdField;
        
        private DocumentType documentTypeField;
        
        private byte[] documentContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string SeqNumber {
            get {
                return this.seqNumberField;
            }
            set {
                this.seqNumberField = value;
                this.RaisePropertyChanged("SeqNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocumentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
                this.RaisePropertyChanged("DocumentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DocumentType DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("DocumentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] DocumentContent {
            get {
                return this.documentContentField;
            }
            set {
                this.documentContentField = value;
                this.RaisePropertyChanged("DocumentContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
        "eway/1.0")]
    public enum DocumentType {
        
        /// <remarks/>
        PDF,
        
        /// <remarks/>
        xHTML,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("MS-DOC")]
        MSDOC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
        "eway/1.0")]
    public partial class SendOutboundFAXAckType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionRefField;
        
        private OutcomeType outcomeField;
        
        private string errorCodeField;
        
        private string errorTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransactionRef {
            get {
                return this.transactionRefField;
            }
            set {
                this.transactionRefField = value;
                this.RaisePropertyChanged("TransactionRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OutcomeType Outcome {
            get {
                return this.outcomeField;
            }
            set {
                this.outcomeField = value;
                this.RaisePropertyChanged("Outcome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
                this.RaisePropertyChanged("ErrorText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
        "eway/1.0")]
    public enum OutcomeType {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failure,
        
        /// <remarks/>
        Acknowledge,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/SendFa" +
        "xGatewayWebService/1.0")]
    public partial class SendFAXResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SendOutboundFAXAckType sendOutboundFAXAckField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/faxgat" +
            "eway/1.0", Order=0)]
        public SendOutboundFAXAckType SendOutboundFAXAck {
            get {
                return this.sendOutboundFAXAckField;
            }
            set {
                this.sendOutboundFAXAckField = value;
                this.RaisePropertyChanged("SendOutboundFAXAck");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFAXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/SendFa" +
            "xGatewayWebService/1.0", Order=0)]
        public FaxSender.SendFAXGatewayWebReference.SendFAX SendFAX;
        
        public SendFAXRequest() {
        }
        
        public SendFAXRequest(FaxSender.SendFAXGatewayWebReference.SendFAX SendFAX) {
            this.SendFAX = SendFAX;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFAXResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.childmaintenance.gsi.gov.uk/futurescheme/outboundCorrespondence/SendFa" +
            "xGatewayWebService/1.0", Order=0)]
        public FaxSender.SendFAXGatewayWebReference.SendFAXResponse SendFAXResponse;
        
        public SendFAXResponse1() {
        }
        
        public SendFAXResponse1(FaxSender.SendFAXGatewayWebReference.SendFAXResponse SendFAXResponse) {
            this.SendFAXResponse = SendFAXResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendFAXGatewayHttpServiceSoapChannel : FaxSender.SendFAXGatewayWebReference.SendFAXGatewayHttpServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendFAXGatewayHttpServiceSoapClient : System.ServiceModel.ClientBase<FaxSender.SendFAXGatewayWebReference.SendFAXGatewayHttpServiceSoap>, FaxSender.SendFAXGatewayWebReference.SendFAXGatewayHttpServiceSoap {
        
        public SendFAXGatewayHttpServiceSoapClient() {
        }
        
        public SendFAXGatewayHttpServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendFAXGatewayHttpServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendFAXGatewayHttpServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendFAXGatewayHttpServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FaxSender.SendFAXGatewayWebReference.SendFAXResponse1 FaxSender.SendFAXGatewayWebReference.SendFAXGatewayHttpServiceSoap.SendFAX(FaxSender.SendFAXGatewayWebReference.SendFAXRequest request) {
            return base.Channel.SendFAX(request);
        }
        
        public FaxSender.SendFAXGatewayWebReference.SendFAXResponse SendFAX(FaxSender.SendFAXGatewayWebReference.SendFAX SendFAX1) {
            FaxSender.SendFAXGatewayWebReference.SendFAXRequest inValue = new FaxSender.SendFAXGatewayWebReference.SendFAXRequest();
            inValue.SendFAX = SendFAX1;
            FaxSender.SendFAXGatewayWebReference.SendFAXResponse1 retVal = ((FaxSender.SendFAXGatewayWebReference.SendFAXGatewayHttpServiceSoap)(this)).SendFAX(inValue);
            return retVal.SendFAXResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FaxSender.SendFAXGatewayWebReference.SendFAXResponse1> FaxSender.SendFAXGatewayWebReference.SendFAXGatewayHttpServiceSoap.SendFAXAsync(FaxSender.SendFAXGatewayWebReference.SendFAXRequest request) {
            return base.Channel.SendFAXAsync(request);
        }
        
        public System.Threading.Tasks.Task<FaxSender.SendFAXGatewayWebReference.SendFAXResponse1> SendFAXAsync(FaxSender.SendFAXGatewayWebReference.SendFAX SendFAX) {
            FaxSender.SendFAXGatewayWebReference.SendFAXRequest inValue = new FaxSender.SendFAXGatewayWebReference.SendFAXRequest();
            inValue.SendFAX = SendFAX;
            return ((FaxSender.SendFAXGatewayWebReference.SendFAXGatewayHttpServiceSoap)(this)).SendFAXAsync(inValue);
        }
    }
}
